name: quyoshli
description: "Quyoshli Project."

version: 1.0.3+4

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Network
  http: ^1.2.2
  http_interceptor: ^2.0.0
  logger: ^2.4.0
  cached_network_image: ^3.4.1

  # GetX
  get: ^4.6.6
  get_storage: ^2.1.1

  # Device
  device_info_plus: ^10.1.0
#  package_info_plus: ^4.0.0

  #UI
  styled_divider: ^1.0.5
  pin_code_fields: ^8.0.1
#  image_picker: ^1.0.7
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.10+1
  dots_indicator: ^3.0.0
  mask_text_input_formatter: ^2.9.0
  fluttertoast: ^8.2.8
  flutter_html: ^3.0.0-beta.2
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  package_info_plus: ^8.0.2

  #Map
#  google_maps_flutter: ^2.9.0


  #URL
  url_launcher: ^6.3.0
  flutter_downloader: ^1.11.8
  share_plus: ^10.0.2
  intl: ^0.19.0
  html: ^0.15.4
  youtube_player_iframe: ^5.2.0
  #
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/dev/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

