final Map<String, String> ruRU = {
  'select': 'Выбрать',
  'uzbek': 'Узбекский',
  'russian': 'Русский',
  'select_lang': 'Выберите предпочтительный язык',
  'currency': 'cум',
  'count_symbol': 'шт.',
  'no': 'Нет',
  'technical_info': "Технические характеристики",
  "catalog": "Каталог",
  "services": "Услуги",
  "service_details": "Детали сервиса",
  "partner": "Партнерство",
  "useful": "Полезное",
  "all": "Все",
  "brands": "Бренды",
  "power": "Мощность",
  "problem": "Проблема",
  "comment": "Комментарии",
  "address": "Адрес",
  "region": "Область",
  "city": "Город / Район",
  "client": "Клиент",
  "full_name": "Ф.И.О.",
  "phone": "Номер телефона",
  "send_request": "Отправить заявку",
  "how_use": "Как пользоваться",
  "information": "Информация",
  "price_per_service": "Цена за услугу (за 1 кВт)",
  "download_file": "Скачать файл",
  "favourites": "Избранное",
  "go_home": "На главную",
  "empty_info": "В списке желаемого пока нет товаров",
  "feedback_fv":
      "Начните с подборок на главной странице или найдите нужный товар",
  "search": "Поиск товаров",
  "empty_info_search": "По вашему запросу нет результатов",
  "accept_request": "Заявка была принята",
  "number_of_request": "Номер заявки",
  "close": "Закрыть",
  "default_sort": "Популярные",
  "brand": "Бренд",
  "filter": "Фильтры",
  "price": "Цена",
  "sorting": "Сортировка",
  "price_from": "От ...",
  "price_to": "До ...",
  "reset": "Сбросить",
  "apply": "Применить",
  "empty_info_products": "В этой категории пока нет товаров",
  "hit": "Хит",
  "basket": "Корзина",
  "empty_info_basket": "В корзине пока нет товаров",
  "ready_solution": "Готовые решения",
  "your_order": "Ваш заказ",
  "items": "товара",
  "product_discount": "Скидка на товары",
  "total": "Итого:",
  "design": "Оформить",
  "products": "Продукты:",
  "in_stock": "В наличии: ",
  "no_items_info":
      "В корзине есть товары, которых нет в наличии. Удалите их из корзины, чтобы оформить заказ",
  "my_orders": "Мои заказы",
  "my_requests": "Мои заявки",
  "feedback": "Обратная связь",
  "settings": "Настройки",
  "language": "Язык",
  "about_app": "О приложении",
  "policy": "Публичная оферта и условия использования",
  "logout": "Выйти из приложения",
  "call_center": "Связаться с колл-центром",
  "contact_tg": "Связаться по Telegram",
  "app_version": "Версия:",
  "not_registered_info": "Вы еще не вошли в систему",
  "please_login": "Пройдите авторизацию для входа",
  "auth": "Авторизация",
  "enter_number": "Введите свой номер телефона, чтобы войти",
  "login": "Войти",
  "logging_by": "Авторизуясь, вы соглашаетесь с",
  "agree_policy": "публичной офертой и условиями использования.",
  "to_number": "На номер ",
  "resend": "Отправить заново",
  "send_sms":
      " было отправлено SMS-сообщение. Введите одноразовый секретный код в сообщении",
  "edit_profile": "Редактировать профиль",
  "lastname": "Фамилия",
  "firstname": "Имя",
  "middle_name": "Отчество",
  "delete_acc": "Удалить профиль",

  "cancel": "Отменить",
  "save": "Сохранить",
  "enter_fullname": "Введите ваше полное имя",
  "no_orders": "Пока заказов нет :(",
  "no_requests": "Пока заявки нет :(",
  "order": "Заказ",
  "payment_status": "Статус оплаты:",
  "order_status": "Статус заказа:",
  "request_status": "Статус заявки:",
  "order_number": "Номер заказа:",
  "request_number": "Номер заявки:",
  "request": "Заявка",
  "request_type": "Тип заявки:",
  "created_time": "Время создания:",
  "order_total": "Сумма заказа:",
  "order_detail": "Детали заказа",
  "request_detail": "Детали заявки",
  "installation_type": "Тип установки:",
  "with_installation": "С установкой",
  "shopping_list": "Список покупок",
  "client_info": "Информация о клиенте",
  "client_type": "Тип клиента:",
  "physical": "Физ. лицо",
  "legal": "Юр. лицо",
  "company_name": "Название компании",
  "inn": "ИНН:",
  "director_fio": "ФИО Директора:",
  "bank": "Банк",
  "mfo": "МФО:",
  "acc_number": "Номер счета",
  "oked": "ОКЭД",
  "email": "Эл. почта:",
  "delivery_details": "Детали доставки",
  "delivery_type": "Тип доставки",
  "delivery": "Доставка",
  "cost_installation": "Стоимость установки:",
  "delivery_cost": "Стоимость доставки:",
  "delivery_address": "Адрес доставки:",
  "pickup": "Самовывоз",
  "pickup_address": "Адрес самовывоза:",
  "with_vat": " с НДС",
  "download_datasheet": "Скачать Datasheet",
  "in_cart": "В корзину",
  "home": "Главная",
  "cart": "Корзина",
  "profile": "Профиль",
  "placing_order": "Оформление заказа",
  "company_length": "Название компании недостаточно длинное",
  "inn_length": "ИНН 8 цифр и более",
  "mfo_length": "МФО 4 цифры или более",
  "invalid_bank_number": "Банковский счет указан неверно",
  "invalid_oked": "ОКЭД неверный",
  "legal_address": "Юридический адрес",
  "invalid_email": "Формат имейла неправильный",
  "invalid_phone": "Номер телефона введен неверно",
  "home_number": "Дом",
  "landmark": "Ориентир",
  "pickup_point": "Пункт выдачи заказов",
  "installation": "Установка",
  "payment": "Оплата",
  "payment_method": "Способ оплаты",
  "cost": "Платеж. с.",
  "cash": "Наличными",
  "pay": "Оплатить",
  "list": "Перечис.",
  "detail_legal": "Реквизиты",
  "send_via_didox": "Отправить через didox",
  "draw_contract": "Оформить договор",
  "self_installation": "Самостоятельная установка",
  "success_registration": "Оформление успешно завершено",
  "download_contract": "Скачать договор",
  "error": "Произошла ошибка",
  "confirm": "Подтверждать",
  "confirm_del": "Вы хотите удалить свою учетную запись?",
  "no_connection": "Нет подключения к интернету",

  "full_description": "Полное описание",
  "product_description": "Описание товара",
};
