final Map<String, String> uzUZ = {
  'select': 'Tanlang',
  'uzbek': "O'zbek tili",
  'russian': 'Rus tili',
  'select_lang': 'Tilni tanlang',
  'currency': "so'm",
  'count_symbol': 'dona',
  'no': "Yo'q",
  'technical_info': "Texnik xususiyatlari",
  "catalog": "Katalog",
  "services": "Xizmatlar",
  "service_details": "Xizmat tafsilotlari",
  "partner": "Hamkorlik",
  "useful": "Foydali",
  "all": "Hammasi",
  "brands": "Brendlar",
  "power": "Quvvat",
  "problem": "Muammo",
  "comment": "Izoh",
  "address": "Manzil",
  "region": "Viloyat",
  "city": "Shahar / Tuman",
  "client": "Mijoz",
  "full_name": "F. I. Sh.",
  "phone": "Telefon raqamingiz",
  "send_request": "Arizani yuboring",
  "how_use": "Qanday foydalanish kerak",
  "information": "Ma'lumot",
  "price_per_service": "Xizmat narxi (1 kVt uchun)",
  "download_file": "Faylni yuklab olish",
  "favourites": "Sevimlilar",
  "go_home": "Bosh sahifa",
  "empty_info": "Ro'yxat bo'sh",
  "feedback_fv": "Asosiy sahifadan boshlang yoki kerakli mahsulotni toping",
  "search": "Mahsulot qidirish",
  "empty_info_search": "So‘rovingiz bo‘yicha hech qanday natija yo‘q",
  "accept_request": "Arizangiz qabul qilindi",
  "number_of_request": "Ariza raqami",
  "close": "Yopish",
  "default_sort": "Mashhur",
  "brand": "Brend",
  "filter": "Filtrlar",
  "price": "Narx",
  "sorting": "Saralash",
  "price_from": "dan...",
  "price_to": "gacha...",
  "reset": "Bekor qilish",
  "apply": "Tasdiqlash",
  "empty_info_products": "Bu boʻlimda mahsulot yoʻq",
  "hit": "Xit",
  "basket": "Savat",
  "empty_info_basket": "Savatingizda hali biror narsa yo‘q",
  "ready_solution": "Tayyor yechimlar",
  "your_order": "Sizning buyurtmangiz",
  "items": "ta maxsulot",
  "product_discount": "Maxsulotlarga chegirma",
  "total": "Jami:",
  "design": "Buyurtma berish",
  "products": "Mahsulotlar:",
  "in_stock": "Sotuvda mavjud: ",
  "no_items_info":
      "Savatingizda sotuvda mavjud bo'lmagan mahsulotlar bor. Toʻlovni amalga oshirish uchun ularni savatdan olib tashlang.",
  "my_orders": "Mening buyurtmalarim",
  "my_requests": "Mening arizalarim",
  "feedback": "Biz bilan bog‘lanish",
  "settings": "Sozlamalar",
  "language": "Til",
  "about_app": "Ilova haqida",
  "policy": "Oferta va foydalanish shartlari",
  "logout": "Chiqish",
  "call_center": "Telefon orqali murojaat qiling",
  "contact_tg": "Telegram orqali bog'lanish",
  "app_version": "Versiya: ",
  "not_registered_info": "Siz hali tizimga kirmagansiz",
  "please_login": "Davom etish uchun tizimga kiring",
  "auth": "Kirish",
  "enter_number": "Kirish uchun telefon raqamingizni kiriting",
  "login": "Kirish",
  "logging_by": "Avtorizatsiyadan o'tish orqali siz ",
  "agree_policy":
      "Oferta va foydalanish shartlariga o'z roziligingizni bildirasiz",
  "to_number": " nomeriga ",
  "resend": "Qayta yuborish",
  "send_sms": " SMS xabar yuborildi. Bir martalik maxfiy kodni kiriting",
  "edit_profile": "Profilni tahrirlash",
  "lastname": "Familiya",
  "firstname": "Ism",
  "middle_name": "Sharif",
  "delete_acc": "Profilni o'chirish",
  "cancel": "Bekor qilish",
  "save": "Saqlash",
  "enter_fullname": "Toʻliq F. I. Sh. kiriting",
  "no_orders": "Buyurtmalar yo'q :(",
  "no_requests": "Arizalar yo'q :(",
  "order": "Buyurtma",
  "payment_status": "To'lov holati:",
  "order_status": "Buyurtma holati:",
  "request_status": "Ariza holati:",
  "order_number": "Buyurtma raqami:",
  "request_number": "Ariza raqami:",
  "request": "Ariza",
  "request_type": "Ariza turi:",
  "created_time": "Yaratilish vaqti:",
  "order_total": "Buyurtma summasi:",
  "order_detail": "Buyurtma tafsilotlari",
  "request_detail": "Ariza tafsilotlari",
  "installation_type": "O'rnatish turi: ",
  "with_installation": "O'rnatish bilan",
  "self_installation": "O'zim o'rnatib olaman",
  "cost_installation": "O'rnatish narxi:",
  "shopping_list": "Xaridlar ro'yxati",
  "client_info": "Mijoz ma'lumotlari",
  "client_type": "Mijoz turi:",
  "physical": "Jis. shaxs",
  "legal": "Yur. shaxs",
  "company_name": "Tashkilot nomi:",
  "inn": "STIR:",
  "director_fio": "Direktorning F.I.Sh.:",
  "bank": "Bank",
  "mfo": "MFO:",
  "acc_number": "Hisob raqami: ",
  "oked": "OKED:",
  "email": "Elektron pochta:",
  "delivery_details": "Yetkazib berish tafsilotlari",
  "delivery_type": "Yetkazib berish turi",
  "delivery": "Yetkazib berish",
  "delivery_cost": "Yetkazib berish narxi:",
  "delivery_address": "Yetkazib berish manzili:",
  "pickup": "Olib ketish",
  "pickup_address": "Olib ketish manzili:",
  "with_vat": " QQS bilan",
  "download_datasheet": "Datasheet'ni yuklab olish",
  "in_cart": "Savatga",
  "home": "Asosiy",
  "cart": "Savat",
  "profile": "Profil",
  "placing_order": "Buyurtma berish",
  "company_length": "Kompaniya nomi uzunligi juda qisqa",
  "inn_length": "STIR 9 ta raqam bo'lishi kerak",
  "mfo_length": "MFO minimum 4 ta raqam bo'lishi kerak",
  "invalid_bank_number": "Bank hisobi noto'g'ri",
  "invalid_oked": "OKED noto'g'ri",
  "legal_address": "Yuridik manzil",
  "invalid_email": "Emailda xatolik bor",
  "invalid_phone": "Telefon raqam noto'g'ri",
  "home_number": "Uy",
  "landmark": "Mo'ljal",
  "pickup_point": "Buyurtmani qabul qilish punkti",
  "installation": "O'rnatish",
  "payment": "To'lov",
  "payment_method": "To'lov usuli",
  "cost": "To'lov tizimi",
  "cash": "Naqd pul",
  "pay": "To'lash",
  "list": "Bank orqali.",
  "detail_legal": "Tafsilotlar",
  "send_via_didox": "Didox orqali yuborish",
  "draw_contract": "Shartnoma tuzish",
  "success_registration": "Buyurtma muvaffaqiyatli qabul qilindi",
  "download_contract": "Shartnomani yuklab olish",
  "error": "Xatolik yuz berdi",
  "confirm": "Tasdiqlash",
  "confirm_del": "Siz profilingizni o'chirib tashlamoqchimisiz?",
  "no_connection": "Internet bilan aloqa yo'q"
};
